# This file was generated by GoReleaser. DO NOT EDIT.
class BigipCli < Formula
  desc ""
  homepage ""
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stobias123/bigip-cli/releases/download/v0.0.6/bigip-cli_0.0.6_macOS_amd64.zip"
    sha256 "f058b4146c662149fd2cfd37a6bc2c8322225fa8cbfb4e4daa2a6a2f3cf6612d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stobias123/bigip-cli/releases/download/v0.0.6/bigip-cli_0.0.6_linux_amd64.zip"
    sha256 "e92f43724f7698d6e369a9f30ba55ef6af2f42db97f93631723d8142e5dce53a"
  end

  def install
    bin.install "bigip"
  end
end
