# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FortiSdkGo < Formula
  desc ""
  homepage ""
  version "1.5.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stobias123/forti-sdk-go/releases/download/v1.5.1/forti-sdk-go_1.5.1_macOS_amd64.zip"
      sha256 "029d52d7bd9b8ffce001342756bd5f1b0eee84a60b1e161ace0822b5ede92385"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stobias123/forti-sdk-go/releases/download/v1.5.1/forti-sdk-go_1.5.1_linux_amd64.zip"
      sha256 "342bd52e638bd4627d8743fee971f113f719f310103be5f8c2f28bc2642e86c6"
    end
  end

  def install
    bin.install "forti-sdk-go"
  end
end
