# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FortiSdkGo < Formula
  desc ""
  homepage ""
  version "1.5.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stobias123/forti-sdk-go/releases/download/v1.5.1/forti-sdk-go_1.5.1_macOS_amd64.zip"
      sha256 "a77321d5d55c19d0151adfb88477116804d8158e2fd95d221c4b488157824759"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stobias123/forti-sdk-go/releases/download/v1.5.1/forti-sdk-go_1.5.1_linux_amd64.zip"
      sha256 "67ac172e56c52fbb23a5fa808dbe78422043159d5221c60818ebb4e5b5fe42b3"
    end
  end

  def install
    bin.install "forti-sdk-go"
  end
end
